import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark" style={{ colorScheme: "dark" }}>
      <body>
        <main className="relative mx-auto flex flex-col items-center justify-center overflow-clip bg-black-100 px-5 sm:px-10">
          <nav
            className="fixed inset-x-0 top-10 z-[5000] mx-auto flex max-w-min items-center justify-center space-x-4 rounded-3xl border border-white/[0.2] bg-black-100 px-5 py-5 shadow-[0px_2px_3px_-1px_rgba(0,0,0,0.1),0px_1px_0px_0px_rgba(25,28,33,0.02),0px_0px_0px_1px_rgba(25,28,33,0.08)]"
            style={{
              opacity: 1,
              willChange: "transform, opacity",
              transform: "none",
            }}
          >
            <a
              className="relative flex items-center space-x-1 text-neutral-600 hover:text-neutral-500 dark:text-neutral-50 dark:hover:text-neutral-300"
              href="#about"
            >
              <span className="!cursor-pointer text-sm">About</span>
            </a>
            <a
              className="relative flex items-center space-x-1 text-neutral-600 hover:text-neutral-500 dark:text-neutral-50 dark:hover:text-neutral-300"
              href="#projects"
            >
              <span className="!cursor-pointer text-sm">Projects</span>
            </a>
            <a
              className="relative flex items-center space-x-1 text-neutral-600 hover:text-neutral-500 dark:text-neutral-50 dark:hover:text-neutral-300"
              href="#contact"
            >
              <span className="!cursor-pointer text-sm">Contact</span>
            </a>
          </nav>

          <div className="w-full max-w-7xl">
            <div className="pb-20 pt-36">
              {/* <div className="">
                <svg
                  className="pointer-events-none absolute animate-spotlight w-[80%] opacity-1"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 3787 2842"
                  fill="none"
                >
                  <g filter="url(#filter)">
                    <ellipse
                      cx="1924.71"
                      cy="273.501"
                      rx="1924.71"
                      ry="273.501"
                      transform="matrix(-0.822377 -0.568943 -0.568943 0.822377 3631.88 2291.09)"
                      fill="white"
                      fillOpacity="0.11"
                    />
                  </g>
                  <defs>
                    <filter
                      id="filter"
                      x="0.860352"
                      y="0.838989"
                      width="3785.16"
                      height="2840.26"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity={0} result="BackgroundImageFix" />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="BackgroundImageFix"
                        result="shape"
                      />
                      <feGaussianBlur
                        stdDeviation={251}
                        result="effect1_foregroundBlur_1065_8"
                      />
                    </filter>
                  </defs>
                </svg>
                <svg
                  className="pointer-events-none absolute  animate-spotlight "
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 3787 2842"
                  fill="none"
                >
                  <g filter="url(#filter)">
                    <ellipse
                      cx="1924.71"
                      cy="273.501"
                      rx="1924.71"
                      ry="273.501"
                      transform="matrix(-0.822377 -0.568943 -0.568943 0.822377 3631.88 2291.09)"
                      fill="purple"
                      fillOpacity="0.21"
                    />
                  </g>
                  <defs>
                    <filter
                      id="filter"
                      x="0.860352"
                      y="0.838989"
                      width="3785.16"
                      height="2840.26"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity={0} result="BackgroundImageFix" />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="BackgroundImageFix"
                        result="shape"
                      />
                      <feGaussianBlur
                        stdDeviation={151}
                        result="effect1_foregroundBlur_1065_8"
                      />
                    </filter>
                  </defs>
                </svg>
                <svg
                  className="pointer-events-none absolute  animate-spotlight"
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 3787 2842"
                  fill="none"
                >
                  <g filter="url(#filter)">
                    <ellipse
                      cx="1924.71"
                      cy="273.501"
                      rx="1924.71"
                      ry="273.501"
                      transform="matrix(-0.822377 -0.568943 -0.568943 0.822377 3631.88 2291.09)"
                      fill="blue"
                      fillOpacity="0.21"
                    />
                  </g>
                  <defs>
                    <filter
                      id="filter"
                      x="0.860352"
                      y="0.838989"
                      width="3785.16"
                      height="2840.26"
                      filterUnits="userSpaceOnUse"
                      colorInterpolationFilters="sRGB"
                    >
                      <feFlood floodOpacity={0} result="BackgroundImageFix" />
                      <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="BackgroundImageFix"
                        result="shape"
                      />
                      <feGaussianBlur
                        stdDeviation={151}
                        result="effect1_foregroundBlur_1065_8"
                      />
                    </filter>
                  </defs>
                </svg>
              </div> */}
            </div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
